BEGIN TRANSACTION;
ALTER TABLE [TB_MUSICOS] DROP CONSTRAINT [FK_TB_MUSICOS_Usuario_UsuarioId];

ALTER TABLE [Usuario] DROP CONSTRAINT [PK_Usuario];

EXEC sp_rename N'[Usuario]', N'TB_USUARIOS', 'OBJECT';

ALTER TABLE [TB_USUARIOS] ADD CONSTRAINT [PK_TB_USUARIOS] PRIMARY KEY ([Id]);

CREATE TABLE [TB_INSTRUMENTO] (
    [Id] int NOT NULL IDENTITY,
    [Nome] varchar(200) NOT NULL,
    CONSTRAINT [PK_TB_INSTRUMENTO] PRIMARY KEY ([Id])
);

CREATE TABLE [TB_MUSICO_INSTRUMENTO] (
    [MusicoId] int NOT NULL,
    [InstrumentoId] int NOT NULL,
    CONSTRAINT [PK_TB_MUSICO_INSTRUMENTO] PRIMARY KEY ([MusicoId], [InstrumentoId]),
    CONSTRAINT [FK_TB_MUSICO_INSTRUMENTO_TB_INSTRUMENTO_InstrumentoId] FOREIGN KEY ([InstrumentoId]) REFERENCES [TB_INSTRUMENTO] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_MUSICO_INSTRUMENTO_TB_MUSICOS_MusicoId] FOREIGN KEY ([MusicoId]) REFERENCES [TB_MUSICOS] ([Id]) ON DELETE CASCADE
);

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Nome') AND [object_id] = OBJECT_ID(N'[TB_INSTRUMENTO]'))
    SET IDENTITY_INSERT [TB_INSTRUMENTO] ON;
INSERT INTO [TB_INSTRUMENTO] ([Id], [Nome])
VALUES (1, 'Saxofone'),
(2, 'Guitarra'),
(3, 'Cavaco'),
(4, 'Violão');
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Nome') AND [object_id] = OBJECT_ID(N'[TB_INSTRUMENTO]'))
    SET IDENTITY_INSERT [TB_INSTRUMENTO] OFF;

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'InstrumentoId', N'MusicoId') AND [object_id] = OBJECT_ID(N'[TB_MUSICO_INSTRUMENTO]'))
    SET IDENTITY_INSERT [TB_MUSICO_INSTRUMENTO] ON;
INSERT INTO [TB_MUSICO_INSTRUMENTO] ([InstrumentoId], [MusicoId])
VALUES (1, 1),
(2, 1);
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'InstrumentoId', N'MusicoId') AND [object_id] = OBJECT_ID(N'[TB_MUSICO_INSTRUMENTO]'))
    SET IDENTITY_INSERT [TB_MUSICO_INSTRUMENTO] OFF;

CREATE INDEX [IX_TB_MUSICO_INSTRUMENTO_InstrumentoId] ON [TB_MUSICO_INSTRUMENTO] ([InstrumentoId]);

ALTER TABLE [TB_MUSICOS] ADD CONSTRAINT [FK_TB_MUSICOS_TB_USUARIOS_UsuarioId] FOREIGN KEY ([UsuarioId]) REFERENCES [TB_USUARIOS] ([Id]) ON DELETE CASCADE;

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20250618231201_instrumentos', N'9.0.6');

COMMIT;
GO

