BEGIN TRANSACTION;
CREATE TABLE [TB_DISPONIBILIDADE] (
    [Id] int NOT NULL IDENTITY,
    [Data] date NULL,
    [Hora] time NOT NULL,
    CONSTRAINT [PK_TB_DISPONIBILIDADE] PRIMARY KEY ([Id])
);

CREATE TABLE [TB_MUSICO_DISPONIBILIDADE] (
    [MusicoId] int NOT NULL,
    [DisponibilidadeId] int NOT NULL,
    CONSTRAINT [PK_TB_MUSICO_DISPONIBILIDADE] PRIMARY KEY ([MusicoId], [DisponibilidadeId]),
    CONSTRAINT [FK_TB_MUSICO_DISPONIBILIDADE_TB_DISPONIBILIDADE_DisponibilidadeId] FOREIGN KEY ([DisponibilidadeId]) REFERENCES [TB_DISPONIBILIDADE] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_TB_MUSICO_DISPONIBILIDADE_TB_MUSICOS_MusicoId] FOREIGN KEY ([MusicoId]) REFERENCES [TB_MUSICOS] ([Id]) ON DELETE CASCADE
);

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Data', N'Hora') AND [object_id] = OBJECT_ID(N'[TB_DISPONIBILIDADE]'))
    SET IDENTITY_INSERT [TB_DISPONIBILIDADE] ON;
INSERT INTO [TB_DISPONIBILIDADE] ([Id], [Data], [Hora])
VALUES (1, '2000-05-15', '14:20:00'),
(2, '2000-05-15', '19:20:00');
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'Id', N'Data', N'Hora') AND [object_id] = OBJECT_ID(N'[TB_DISPONIBILIDADE]'))
    SET IDENTITY_INSERT [TB_DISPONIBILIDADE] OFF;

IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'DisponibilidadeId', N'MusicoId') AND [object_id] = OBJECT_ID(N'[TB_MUSICO_DISPONIBILIDADE]'))
    SET IDENTITY_INSERT [TB_MUSICO_DISPONIBILIDADE] ON;
INSERT INTO [TB_MUSICO_DISPONIBILIDADE] ([DisponibilidadeId], [MusicoId])
VALUES (1, 1),
(2, 1);
IF EXISTS (SELECT * FROM [sys].[identity_columns] WHERE [name] IN (N'DisponibilidadeId', N'MusicoId') AND [object_id] = OBJECT_ID(N'[TB_MUSICO_DISPONIBILIDADE]'))
    SET IDENTITY_INSERT [TB_MUSICO_DISPONIBILIDADE] OFF;

CREATE INDEX [IX_TB_MUSICO_DISPONIBILIDADE_DisponibilidadeId] ON [TB_MUSICO_DISPONIBILIDADE] ([DisponibilidadeId]);

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20250619000604_disponibilidade', N'9.0.6');

COMMIT;
GO

